#!/usr/bin/env bash
#This Bash script loops from 1 to 10, displays bad luck for 4th loop, good luck for 8th loop, and Best School for other iterations.
i="0"
while [ $i -lt 10 ]
do
	if (( i == 3)); then
		echo "bad luck"
	elif (( i == 7)); then
		echo "good luck"
	else
		echo "Best School"
	fi
	i=$((i+1))
done
