#!/usr/bin/env bash
#This Bash script that displays numbers from 1 to 20. It displays 4 and then bad luck from china for the 4th loop, 9 and then bad luck from Japanfor the 9th loop, 17 and then bad luck from Italy for the 17th loop.
i="1"
while [ $i -lt 21 ]
do
echo $i
case $i in
"4" )
echo "bad luck from China"
;;
"9" )
echo "bad luck from Japan"
;;
"17")
echo "bad luck from Italy"
;;
esac
i=$((i+1))
done
