#!/usr/bin/env bash
#This Bash script displays the time for 12 hours 59 minutes. It displays hours from 0 to 12 and minutes from 1 to 59.
hour="0"
min="1"

while [ $hour -lt 13 ]
do
echo "Hour: $hour"
while [ $min -lt 60 ]
do
echo $min
min=$((min+1))
done
min="1"
hour=$((hour+1))
done
